import {execFileSync,spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const dir='docs/media/launch/reel-v06';
const file=`${dir}/gyro-launch-16x9-15s-en-v06.mp4`;
const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',file]));
const v=probe.streams.find(s=>s.codec_type==='video'),a=probe.streams.find(s=>s.codec_type==='audio');
const assert=(ok,message)=>{if(!ok)throw Error(message)};
assert(v.width===1920&&v.height===1080,'Wrong dimensions');
assert(v.r_frame_rate==='60/1'&&Number(v.nb_frames)===900,'Wrong cadence or frame count');
assert(Number(v.duration)===15&&Number(probe.format.duration)===15,'Wrong duration');
assert(a.channels===2&&Number(a.sample_rate)===48000,'Wrong stereo/sample rate');
const md5=execFileSync('ffmpeg',['-v','error','-ss','13','-i',file,'-t','2','-an','-f','framemd5','-'],{encoding:'utf8'});
const hold=md5.split('\n').filter(l=>/^0,/.test(l)).map(l=>l.split(',').at(-1).trim());
assert(hold.length===120,'Closing hold must contain120 frames');
assert(new Set(hold).size===1,'Decoded closing hold is not pixel-identical');
const log=spawnSync('ffmpeg',['-hide_banner','-i',file,'-vf','blackdetect=d=0.02:pix_th=0.05','-af','ebur128=peak=true','-f','null','-'],{encoding:'utf8',maxBuffer:8e6});
assert(log.status===0,'Media decode failed');
assert(!log.stderr.includes('black_start:'),'Unexpected black frames');
writeFileSync(`${dir}/final-media-analysis.log`,log.stderr);
const summary=log.stderr.slice(log.stderr.lastIndexOf('Summary:'));
const integratedLUFS=Number(summary.match(/I:\s*([-\d.]+) LUFS/)?.[1]);
const truePeakDBTP=Number(summary.match(/Peak:\s*([-\d.]+) dBFS/)?.[1]);
assert(Number.isFinite(integratedLUFS)&&Math.abs(integratedLUFS+15)<=.6,'Audio loudness outside target range');
assert(Number.isFinite(truePeakDBTP)&&truePeakDBTP<=-1.5,'Decoded audio true peak above ceiling');
const poses=JSON.parse(readFileSync(`${dir}/final-poses.json`));
for(const state of poses)for(const [id,p]of Object.entries(state.layers))assert(Object.values(p).every(Number.isFinite),`Non-finite pose at ${state.frame}:${id}`);
const report={file,sha256:createHash('sha256').update(readFileSync(file)).digest('hex'),video:{width:v.width,height:v.height,fps:v.r_frame_rate,frames:Number(v.nb_frames),duration:Number(v.duration),codec:v.codec_name,pixelFormat:v.pix_fmt},audio:{codec:a.codec_name,channels:a.channels,sampleRate:Number(a.sample_rate),duration:Number(a.duration),integratedLUFS,truePeakDBTP},closingHold:{startFrame:780,endFrame:899,frames:hold.length,uniqueDecodedFrames:new Set(hold).size},mediaDecodes:true,unexpectedBlackFrames:false,poseFramesValidated:poses.length,reviewLimit:'Frame and numerical audio review; subjective real-time headphone audition has not been performed by an available tool.'};
writeFileSync(`${dir}/verification.json`,JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
