// Roles belong to Gyro, never to a specific grammar or provider.
export const tokenRoles = [
  "comment",
  "docComment",
  "keyword",
  "controlKeyword",
  "storageKeyword",
  "type",
  "builtinType",
  "class",
  "interface",
  "struct",
  "enum",
  "enumMember",
  "typeParameter",
  "function",
  "functionCall",
  "method",
  "methodCall",
  "constructor",
  "parameter",
  "variable",
  "localVariable",
  "globalVariable",
  "constant",
  "property",
  "field",
  "namespace",
  "module",
  "package",
  "string",
  "templateString",
  "escapeCharacter",
  "number",
  "boolean",
  "null",
  "undefined",
  "operator",
  "punctuation",
  "delimiter",
  "decorator",
  "annotation",
  "attribute",
  "regex",
  "tag",
  "htmlAttribute",
  "cssSelector",
  "cssProperty",
  "cssValue",
  "cssUnit",
  "markdownHeading",
  "markdownBold",
  "markdownItalic",
  "markdownLink",
  "markdownCode",
  "markdownQuote",
  "markdownList",
  "configKey",
  "configValue",
  "jsonKey",
  "yamlAnchor",
  "yamlAlias",
  "sqlKeyword",
  "sqlTable",
  "sqlColumn",
  "sqlFunction",
  "graphqlType",
  "graphqlField",
  "graphqlVariable",
  "graphqlDirective",
  "dockerInstruction",
  "shellCommand",
  "shellFlag",
  "envVariable",
  "gitHash",
  "gitRef",
  "conflictMarker",
  "diffAdded",
  "diffRemoved",
  "diffModified",
  "diffHeader",
  "diffChunk",
  "deprecated",
  "invalid",
] as const;
export type TokenRole = (typeof tokenRoles)[number];
export type GyroSyntaxTheme = Record<TokenRole, string>;
// Each family gets its own hue so neighbouring roles (a YAML key and its
// value, a JSX tag and its props, a call and its arguments) never blur.
const families: Record<string, readonly TokenRole[]> = {
  comment: ["comment", "docComment", "markdownQuote", "deprecated"],
  keyword: [
    "keyword",
    "controlKeyword",
    "storageKeyword",
    "sqlKeyword",
    "dockerInstruction",
    "graphqlDirective",
    "markdownList",
  ],
  type: [
    "type",
    "builtinType",
    "class",
    "interface",
    "struct",
    "enum",
    "typeParameter",
    "namespace",
    "module",
    "package",
    "sqlTable",
    "graphqlType",
    "cssSelector",
  ],
  function: [
    "function",
    "functionCall",
    "method",
    "methodCall",
    "constructor",
    "sqlFunction",
    "shellCommand",
    "markdownHeading",
    "diffHeader",
  ],
  string: [
    "string",
    "templateString",
    "markdownCode",
    "configValue",
    "cssValue",
    "diffAdded",
  ],
  number: [
    "number",
    "boolean",
    "null",
    "undefined",
    "constant",
    "enumMember",
    "cssUnit",
    "yamlAnchor",
    "yamlAlias",
    "gitHash",
  ],
  property: [
    "property",
    "field",
    "attribute",
    "tag",
    "cssProperty",
    "configKey",
    "jsonKey",
    "graphqlField",
    "sqlColumn",
  ],
  accent: [
    "escapeCharacter",
    "regex",
    "markdownLink",
    "gitRef",
    "diffChunk",
    "shellFlag",
    "envVariable",
  ],
  warm: [
    "parameter",
    "globalVariable",
    "decorator",
    "annotation",
    "htmlAttribute",
    "graphqlVariable",
    "diffModified",
  ],
  muted: ["operator", "punctuation", "delimiter"],
  invalid: ["invalid", "conflictMarker", "diffRemoved"],
};
const palettes = {
  dark: {
    foreground: "D7D9DE",
    comment: "7D8590",
    keyword: "C792EA",
    type: "E5C07B",
    function: "6CB6FF",
    string: "98C987",
    number: "F2A172",
    property: "F07A83",
    accent: "56C8D8",
    warm: "E9B872",
    muted: "A3AAB5",
    invalid: "FF6B6B",
  },
  light: {
    foreground: "24272D",
    comment: "6A737D",
    keyword: "8A3FC7",
    type: "946200",
    function: "1D5FD1",
    string: "237A3B",
    number: "B5530D",
    property: "C62E45",
    accent: "0B7A8A",
    warm: "9A5B00",
    muted: "57606A",
    invalid: "CF222E",
  },
};
export function createSyntaxTheme(mode: "dark" | "light"): GyroSyntaxTheme {
  const palette = palettes[mode];
  const result = Object.fromEntries(
    tokenRoles.map((role) => [role, palette.foreground]),
  ) as GyroSyntaxTheme;
  for (const [family, roles] of Object.entries(families))
    for (const role of roles)
      result[role] = palette[family as keyof typeof palette];
  return result;
}
export const tokenRoleAliases: Record<string, TokenRole> = {
  "comment.doc": "docComment",
  "keyword.control": "controlKeyword",
  storage: "storageKeyword",
  "keyword.type": "builtinType",
  "constant.language": "boolean",
  "type.identifier": "type",
  "type.lifetime": "parameter",
  "function.macro": "function",
  "entity.name.function": "function",
  "entity.name.type": "type",
  "entity.name.class": "class",
  "variable.parameter": "parameter",
  "variable.other.constant": "constant",
  "variable.other": "variable",
  "string.escape": "escapeCharacter",
  "string.escape.invalid": "invalid",
  "string.key.json": "jsonKey",
  "string.value.json": "string",
  "string.regexp": "regex",
  regexp: "regex",
  "delimiter.bracket": "delimiter",
  "attribute.name": "attribute",
  "attribute.value": "string",
  "attribute.value.number": "number",
  "attribute.value.unit": "cssUnit",
  metatag: "decorator",
  tag: "tag",
  "number.hex": "number",
  "keyword.json": "boolean",
  "tag.css": "cssSelector",
  "attribute.name.css": "cssProperty",
  "attribute.name.scss": "cssProperty",
  "attribute.name.less": "cssProperty",
  "keyword.yaml": "boolean",
  "type.yaml": "configKey",
  "namespace.yaml": "yamlAnchor",
  "tag.yaml": "decorator",
  operators: "operator",
  "attribute.name.html": "htmlAttribute",
  "attribute.name.jsx": "htmlAttribute",
  "delimiter.angle": "punctuation",
  "variable.md": "markdownCode",
  "variable.source.md": "markdownCode",
  predefined: "function",
  "variable.predefined": "builtinType",
  "string.link": "markdownLink",
  "string.md": "markdownCode",
  "keyword.md": "markdownHeading",
  "markup.heading": "markdownHeading",
  "markup.bold": "markdownBold",
  "markup.italic": "markdownItalic",
  strong: "markdownBold",
  emphasis: "markdownItalic",
  meta: "diffHeader",
  inserted: "diffAdded",
  deleted: "diffRemoved",
  invalid: "invalid",
};
export function normalizeTokenRole(token: string): TokenRole {
  let key = token;
  while (key) {
    if ((tokenRoles as readonly string[]).includes(key))
      return key as TokenRole;
    if (tokenRoleAliases[key]) return tokenRoleAliases[key]!;
    key = key.slice(0, Math.max(0, key.lastIndexOf(".")));
  }
  return "variable";
}
