// Roles belong to Gyro, never to a specific grammar or provider.
export const tokenRoles = [
  "comment",
  "docComment",
  "keyword",
  "controlKeyword",
  "storageKeyword",
  "type",
  "builtinType",
  "class",
  "interface",
  "struct",
  "enum",
  "enumMember",
  "typeParameter",
  "function",
  "functionCall",
  "method",
  "methodCall",
  "constructor",
  "parameter",
  "variable",
  "localVariable",
  "globalVariable",
  "constant",
  "property",
  "field",
  "namespace",
  "module",
  "package",
  "string",
  "templateString",
  "escapeCharacter",
  "number",
  "boolean",
  "null",
  "undefined",
  "operator",
  "punctuation",
  "delimiter",
  "decorator",
  "annotation",
  "attribute",
  "regex",
  "tag",
  "htmlAttribute",
  "cssSelector",
  "cssProperty",
  "cssValue",
  "cssUnit",
  "markdownHeading",
  "markdownBold",
  "markdownItalic",
  "markdownLink",
  "markdownCode",
  "markdownQuote",
  "markdownList",
  "configKey",
  "configValue",
  "jsonKey",
  "yamlAnchor",
  "yamlAlias",
  "sqlKeyword",
  "sqlTable",
  "sqlColumn",
  "sqlFunction",
  "graphqlType",
  "graphqlField",
  "graphqlVariable",
  "graphqlDirective",
  "dockerInstruction",
  "shellCommand",
  "shellFlag",
  "envVariable",
  "gitHash",
  "gitRef",
  "conflictMarker",
  "diffAdded",
  "diffRemoved",
  "diffModified",
  "diffHeader",
  "diffChunk",
  "deprecated",
  "invalid",
] as const;
export type TokenRole = (typeof tokenRoles)[number];
export type GyroSyntaxTheme = Record<TokenRole, string>;
const families: Record<string, readonly TokenRole[]> = {
  comment: ["comment", "docComment", "markdownQuote", "deprecated"],
  keyword: [
    "keyword",
    "controlKeyword",
    "storageKeyword",
    "boolean",
    "null",
    "undefined",
    "sqlKeyword",
    "dockerInstruction",
    "graphqlDirective",
  ],
  type: [
    "type",
    "builtinType",
    "class",
    "interface",
    "struct",
    "enum",
    "typeParameter",
    "namespace",
    "module",
    "package",
    "sqlTable",
    "graphqlType",
    "diffChunk",
  ],
  function: [
    "function",
    "functionCall",
    "method",
    "methodCall",
    "constructor",
    "sqlFunction",
    "shellCommand",
    "markdownHeading",
    "diffHeader",
  ],
  string: [
    "string",
    "templateString",
    "markdownCode",
    "configValue",
    "cssValue",
  ],
  number: ["number", "cssUnit", "diffAdded"],
  accent: [
    "constant",
    "enumMember",
    "escapeCharacter",
    "property",
    "field",
    "attribute",
    "htmlAttribute",
    "cssProperty",
    "configKey",
    "jsonKey",
    "graphqlField",
    "regex",
    "yamlAnchor",
    "yamlAlias",
    "markdownLink",
    "gitRef",
  ],
  warm: [
    "parameter",
    "globalVariable",
    "decorator",
    "annotation",
    "tag",
    "cssSelector",
    "graphqlVariable",
    "shellFlag",
    "envVariable",
    "gitHash",
    "markdownList",
    "diffModified",
  ],
  invalid: ["invalid", "conflictMarker", "diffRemoved"],
};
const palettes = {
  dark: {
    foreground: "D7D9DE",
    comment: "8B949E",
    keyword: "FF7B72",
    type: "2DD4BF",
    function: "C7A0FF",
    string: "A5D6FF",
    number: "9ECE6A",
    accent: "79C0FF",
    warm: "FF9E64",
    invalid: "FF7B72",
  },
  light: {
    foreground: "24272D",
    comment: "626B78",
    keyword: "B42318",
    type: "0F766E",
    function: "6D28D9",
    string: "0B6E99",
    number: "2B7A4B",
    accent: "1F66D1",
    warm: "B43B0B",
    invalid: "B42318",
  },
};
export function createSyntaxTheme(mode: "dark" | "light"): GyroSyntaxTheme {
  const palette = palettes[mode];
  const result = Object.fromEntries(
    tokenRoles.map((role) => [role, palette.foreground]),
  ) as GyroSyntaxTheme;
  for (const [family, roles] of Object.entries(families))
    for (const role of roles)
      result[role] = palette[family as keyof typeof palette];
  return result;
}
export const tokenRoleAliases: Record<string, TokenRole> = {
  "comment.doc": "docComment",
  "keyword.control": "controlKeyword",
  storage: "storageKeyword",
  "keyword.type": "builtinType",
  "type.identifier": "type",
  "type.lifetime": "parameter",
  "function.macro": "function",
  "entity.name.function": "function",
  "entity.name.type": "type",
  "entity.name.class": "class",
  "variable.parameter": "parameter",
  "variable.other.constant": "constant",
  "variable.other": "variable",
  "string.escape": "escapeCharacter",
  "string.escape.invalid": "invalid",
  "string.key.json": "jsonKey",
  "string.value.json": "string",
  "string.regexp": "regex",
  regexp: "regex",
  "delimiter.bracket": "delimiter",
  "attribute.name": "attribute",
  "attribute.value": "string",
  "attribute.value.number": "number",
  "attribute.value.unit": "cssUnit",
  metatag: "decorator",
  tag: "tag",
  "number.hex": "number",
  "keyword.json": "keyword",
  "tag.css": "cssSelector",
  "attribute.name.css": "cssProperty",
  "attribute.name.scss": "cssProperty",
  "attribute.name.less": "cssProperty",
  "keyword.yaml": "configKey",
  "type.yaml": "yamlAnchor",
  "string.link": "markdownLink",
  "string.md": "markdownCode",
  "keyword.md": "markdownHeading",
  "markup.heading": "markdownHeading",
  "markup.bold": "markdownBold",
  "markup.italic": "markdownItalic",
  strong: "markdownBold",
  emphasis: "markdownItalic",
  meta: "diffHeader",
  inserted: "diffAdded",
  deleted: "diffRemoved",
  invalid: "invalid",
};
export function normalizeTokenRole(token: string): TokenRole {
  let key = token;
  while (key) {
    if ((tokenRoles as readonly string[]).includes(key))
      return key as TokenRole;
    if (tokenRoleAliases[key]) return tokenRoleAliases[key]!;
    key = key.slice(0, Math.max(0, key.lastIndexOf(".")));
  }
  return "variable";
}
